name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # nightly builds

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        juce-branch: [master, develop]
    steps:
      - name: Checkout jucey_bonjour
        uses: actions/checkout@v2
      - name: Checkout JUCE
        uses: actions/checkout@v2
        with:
          repository: juce-framework/JUCE
          path: tests
          ref: ${{ matrix.juce-branch }}
