name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # nightly builds

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode-version: [10.3] #[10.3, 11, 11.1, 11.2.1, 11.3.1, 11.4]
    steps:
      - name: Checkout jucey_bonjour
        uses: actions/checkout@v2
      - name: Checkout JUCE
        uses: actions/checkout@v2
        with:
          repository: "https://github.com/juce-framework/JUCE.git"
