name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # nightly builds

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode-version: [10.3, 11, 11.1, 11.2.1, 11.3.1, 11.4]
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        working-directory: ./tests
        run: |
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode-version }}.app
          ./run_tests_mac.sh
